;-----------------------------------------------------------------------
include     windows.inc
include     resources.inc

;-----------------------------------------------------------------------
include     kernel32.inc
includelib  kernel32.lib

include     user32.inc
includelib  user32.lib

include     advapi32.inc
includelib  advapi32.lib

include     gdi32.inc
includelib  gdi32.lib

;-----------------------------------------------------------------------
include     macros.asm

include     masm32.inc
includelib  masm32.lib

include     biglib.inc
includelib  biglib.lib

include     THS.inc
includelib  THS.lib

include     TES.inc
includelib  TES.lib

include     fileio.inc
includelib  fileio.lib

;-----------------------------------------------------------------------
